/**
 * Traditional Tambola / Housie number nicknames (1–90).
 */
export const TAMBOLA_CALLOUTS: Record<number, string> = {
  1:  "Kelly's eye",
  2:  "One little duck",
  3:  "Cup of tea",
  4:  "Knock at the door",
  5:  "Man alive",
  6:  "Half a dozen",
  7:  "Lucky Seven",
  8:  "Garden gate",
  9:  "Doctor's orders",
  10: "A big fat hen",
  11: "Legs eleven",
  12: "One Dozen",
  13: "Unlucky for some",
  14: "Valentine's Day",
  15: "Young and keen",
  16: "Sweet Sixteen",
  17: "Dancing queen",
  18: "Coming of age",
  19: "Goodbye teens",
  20: "One score",
  21: "Key of the door",
  22: "Two little ducks",
  23: "Thee and me",
  24: "Two Dozen",
  25: "Duck and dive",
  26: "Pick and mix",
  27: "Gateway to Heaven",
  28: "Over weight",
  29: "Rise and shine",
  30: "Dirty Gertie",
  31: "Get up and run",
  32: "Buckle my shoe",
  33: "All the threes",
  34: "Ask for more",
  35: "Jump and jive",
  36: "Three dozen",
  37: "More than eleven",
  38: "Christmas cake",
  39: "Steps",
  40: "Life begins at forty",
  41: "Time for fun",
  42: "Winnie the Pooh",
  43: "Down on your knees",
  44: "Droopy drawers",
  45: "Halfway there",
  46: "Up to tricks",
  47: "Four and seven",
  48: "Four dozen",
  49: "PC 49",
  50: "Half a century",
  51: "Tweak of the thumb",
  52: "Deck of cards",
  53: "Stuck in the tree",
  54: "Clean the floor",
  55: "Snakes alive",
  56: "Was she worth it",
  57: "Heinz varieties",
  58: "Make them wait",
  59: "Brighton Line",
  60: "Five dozen",
  61: "Bakers bun",
  62: "Turn the screw",
  63: "Tickle me",
  64: "Red raw",
  65: "Old age pension",
  66: "Clickety click",
  67: "Made in heaven",
  68: "Saving grace",
  69: "Any way up",
  70: "Three score and ten",
  71: "Bang on the drum",
  72: "Six dozen",
  73: "Queen bee",
  74: "Hit the floor",
  75: "Strive and strive",
  76: "Trombones",
  77: "Sunset strip",
  78: "Thirty-nine more steps",
  79: "One more time",
  80: "Eight and blank",
  81: "Stop and run",
  82: "Straight on through",
  83: "Time for tea",
  84: "Seven dozen",
  85: "Staying alive",
  86: "Between the sticks",
  87: "Torquay in Devon",
  88: "Two fat ladies",
  89: "Nearly there",
  90: "Top of the shop",
};

export function getCallout(num: number): string {
  const nickname = TAMBOLA_CALLOUTS[num];
  if (!nickname) return `${num}`;
  return `${nickname}... ${num}!`;
}
