/**
 * Traditional Tambola / Housie number nicknames (1–90).
 */
export const TAMBOLA_CALLOUTS: Record<number, string> = {
  1:  "Sabka Malik Ek",
  2:  "Hum do hamare do",
  3:  "Teen tigada, kaam bigada",
  4:  "Chaar diwaari",
  5:  "Hum Paanch",
  6:  "Ye lagaya chakka",
  7:  "Lucky Seven",
  8:  "Thaath baath number aath",
  9:  "Doctor's orders",
  10: "Dus numbari",
  11: "Ek aur ek gyarah",
  12: "One Dozen",
  13: "Unlucky for some",
  14: "Valentine's Day",
  15: "Independence Day",
  16: "Sweet Sixteen",
  17: "Khatra Satrah",
  18: "Voting age",
  19: "Last of the teens",
  20: "Blind Twenty / T20 Cricket",
  21: "Shadi ki umar",
  22: "Two little ducks",
  23: "You and me",
  24: "Two Dozen",
  25: "Silver Jubilee",
  26: "Republic Day",
  27: "Gateway to Heaven",
  28: "Out of state",
  29: "In your prime",
  30: "Naughty thirty",
  31: "Baskin Robbins",
  32: "Battis Daant",
  33: "All the threes",
  34: "Dil maange more",
  35: "Flirty thirty-five",
  36: "Chhattis ka aankda",
  37: "Mixed luck",
  38: "Overweight",
  39: "Watch your waistline",
  40: "Life begins at forty",
  41: "Life's fun at 41",
  42: "Quit India",
  43: "Climb a tree",
  44: "Dil ke chor",
  45: "Halfway there",
  46: "Up to tricks",
  47: "Aazadi ka saal",
  48: "Chaar dozen",
  49: "Unchaas, maro kachaas",
  50: "Half century",
  51: "Shagun ka ekyaavan",
  52: "Taash ke patte",
  53: "Paanch aur teen",
  54: "Clean the floor",
  55: "Dono bhai",
  56: "Chhappan inch ka seena",
  57: "Banegi baat",
  58: "Retiring soon",
  59: "Just behind sixty",
  60: "Retirement ki umar",
  61: "Done and dusted",
  62: "Click the shoe",
  63: "Tickle me",
  64: "Catch the chor",
  65: "Old age pension",
  66: "Chakke pe chakka",
  67: "Made in heaven",
  68: "Mota seth",
  69: "Ulta Pulta",
  70: "Sattar minute",
  71: "Bang the drum",
  72: "Lucky bindu",
  73: "Under the tree",
  74: "Still want more",
  75: "Diamond Jubilee",
  76: "Lucky six",
  77: "Hum Saath Saath Hain",
  78: "Heaven's gate",
  79: "One more time",
  80: "Gandhi's breakfast",
  81: "Done dana dan",
  82: "Fat lady with a duck",
  83: "Time for tea",
  84: "Khel mein twist",
  85: "Staying alive",
  86: "Pick up sticks",
  87: "Phataphat",
  88: "Do moti auratein",
  89: "All but one",
  90: "Top of the house",
};

export function getCallout(num: number): string {
  const nickname = TAMBOLA_CALLOUTS[num];
  if (!nickname) return `${num}`;
  return `${nickname}... ${num}!`;
}
